# Numpy  

In [5]:
import numpy as np
#how to create an array
arr=np.array([[1 , 2 ,3 , 4] , [6 , 7 , 8 , 9] , [10 , 11 , 12 , 13]])
arr

array([[ 1,  2,  3,  4],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [6]:
# to check the dimension of array
arr.ndim

2

In [7]:
#to check the size
arr.size

12

In [8]:
#to check the datatype of array
arr.dtype

dtype('int32')

In [9]:
arr=np.array([[1 , 1 , 1, 1] , [1 , 1 , 1 , 1] , [1 , 1 , 1 , 1]])
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
#how to create ones array
arr=np.ones(( 3 , 4) , dtype=int)
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
#how to create zeros array 
arr=np.zeros((3 , 4) , dtype=int)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [22]:
#arange()
li=list(range(1 , 20))
li
arr=np.arange(1 ,13 , 2)
arr

array([ 1,  3,  5,  7,  9, 11])

In [26]:
#linespace
arr=np.linspace(1 , 5 , 4)
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [34]:
#reshape
arr=np.arange(1 , 13).reshape(3 , 4)
arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
#ravel
arr=np.arange(1 , 13).reshape(3 , 4)
arr=arr.ravel()
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [37]:
#flatten
arr=np.arange(1 , 13).reshape(3 , 4)
arr=arr.flatten()
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
#transpose
arr=np.arange(1 , 13).reshape(3 , 4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
arr=arr.transpose()
arr

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [41]:
# Mathematical operations in numpy


In [46]:
arr1=np.arange(1 , 13).reshape(3 , 4)
arr2=np.arange(13 , 25).reshape(3 , 4)
arr1


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
arr2

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [48]:
# addtion
arr1 + arr2

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [49]:
np.add(arr1 , arr2)

array([[14, 16, 18, 20],
       [22, 24, 26, 28],
       [30, 32, 34, 36]])

In [50]:
#subtraction
arr2-arr1

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [51]:
arr1-arr2

array([[-12, -12, -12, -12],
       [-12, -12, -12, -12],
       [-12, -12, -12, -12]])

In [52]:
np.subtract(arr2 , arr1)

array([[12, 12, 12, 12],
       [12, 12, 12, 12],
       [12, 12, 12, 12]])

In [53]:
#multiply
arr1*arr2

array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

In [54]:
np.multiply(arr1 , arr2)

array([[ 13,  28,  45,  64],
       [ 85, 108, 133, 160],
       [189, 220, 253, 288]])

In [58]:
#divide
arr2/arr1

array([[13.        ,  7.        ,  5.        ,  4.        ],
       [ 3.4       ,  3.        ,  2.71428571,  2.5       ],
       [ 2.33333333,  2.2       ,  2.09090909,  2.        ]])

In [57]:
np.divide(arr2 , arr1)

array([[13.        ,  7.        ,  5.        ,  4.        ],
       [ 3.4       ,  3.        ,  2.71428571,  2.5       ],
       [ 2.33333333,  2.2       ,  2.09090909,  2.        ]])

In [60]:
# max , min functions in numpy
arr=np.arange(1 , 11).reshape(2 , 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [61]:
arr.max()

10

In [62]:
arr.min()

1

In [63]:
arr.argmax()

9

In [65]:
arr.max(axis=0)

array([ 6,  7,  8,  9, 10])

In [66]:
arr.min(axis=1)

array([1, 6])

In [67]:
# column -0
# row - 1

In [69]:
#sum
np.sum(arr)

55

In [70]:
#mean
np.mean(arr)

5.5

In [71]:
#sqrt
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766]])

In [72]:
#std
np.std(arr)

2.8722813232690143

In [73]:
#log
np.log(arr)

array([[0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509]])

In [75]:
#numpy array slicing
arr=np.arange(1 , 101).reshape(10 , 10)
arr

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [76]:
arr[ 2 : 9,  2:8]

array([[23, 24, 25, 26, 27, 28],
       [33, 34, 35, 36, 37, 38],
       [43, 44, 45, 46, 47, 48],
       [53, 54, 55, 56, 57, 58],
       [63, 64, 65, 66, 67, 68],
       [73, 74, 75, 76, 77, 78],
       [83, 84, 85, 86, 87, 88]])

In [78]:
arr[8: , :]

array([[ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [80]:
arr[4:6 , 4:6]

array([[45, 46],
       [55, 56]])

In [84]:
#concatenation and split
arr1=np.arange(1 ,11).reshape(5 ,2)
arr2=np.arange(11 , 21).reshape(5 , 2)
np.concatenate((arr1 , arr2),axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [87]:
arr1

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [89]:
arr=np.arange(1 , 7)
arr

array([1, 2, 3, 4, 5, 6])

In [90]:
np.split(arr , 3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [93]:
import random
# random function
np.random.random(5)

array([0.07743587, 0.61749436, 0.41104387, 0.84648095, 0.26006665])

In [94]:
np.random.random((3 ,3))

array([[0.06113264, 0.32726234, 0.73249016],
       [0.23385135, 0.2843537 , 0.06274055],
       [0.44602615, 0.22997715, 0.93616511]])

In [99]:

np.random.randint(1 , 4 ,(3 , 3))

array([[1, 1, 1],
       [1, 3, 3],
       [1, 1, 2]])